### ISSUE TITLE
无法显示媒体中的图片

### ISSUE THREAD

**Issue by sjzbim** [nvPress/nvPress#1]
熊猫大佬您好，前几天突然无法显示服务器中的图片了，外链没问题，媒体中的图片都显示为❌

**Comment by conanliuhuan** [comment]
1、确保您使用的是dockerhub上拉取的最新版
2、检查后台：设置-常规-站点地址，若地址最末尾有反斜杠/，删除它。仅保留 `http://www.xxxx.com` 即可，最后的/不需要

请按上述步骤操作，是否解决请回复

**Comment by sjzbim** [comment]
就是这里的问题，我的地址写错了～谢谢您～
还有个小问题，就是在编辑文章的时候，标题中如果有</body>这样的代码，就会显示为&lt;/body&gt;
请教一下，这个如何解决？谢谢

**Comment by conanliuhuan** [comment]
与标题相关的讨论已经结束，有新的问题请提交新的Issue。
提交时请包涵：重现步骤、期待的结果、实际结果、示例链接。
