### ISSUE TITLE
[Next]评论后内容可见失效

### ISSUE THREAD

**Issue by LegnaOS** [nvPress/nvPress#10]
## 受影响版本：
NVpress Next 5.23 发布
## 配合的主题：
Samsara 2.0.5 ES 5.23 发布
## 问题描述：
当用户登录时，评论回复文章时，评论回复后内容可见功能时效，即使早期已评论用户也无法查看此模块内容

**Comment by conanliuhuan** [comment]
相同issue：https://github.com/nvPress/nvPress/issues/9
