### ISSUE TITLE
导入导出

### ISSUE THREAD

**Issue by Chenmo1212** [nvPress/nvPress#2]
感谢大佬开发的平台，想问一下，有导入导出功能吗？想从wordpress迁移过来，但是没有导入导出的话，很头疼啊

**Comment by conanliuhuan** [comment]
没有。原理不同，数据存储方式也完全不同，wordpress是html字符串存储的文章内容，nvPress是存储的json数据，没办法相互转换。即使基于某个规则进行转换，也会导致数据大量丢失。因此建议手动处理一遍。
未来也不会提供此类的转换工具。不过nvPress提供了插件功能，如果有第三方开发者开发相关插件，也是有可能的
