### ISSUE TITLE
[Next]nv-admin 管理后台中手动添加用户提示请求失败

### ISSUE THREAD

**Issue by LegnaOS** [nvPress/nvPress#4]
Next 版NVPRESS 框架中，使用 S 主题 2.0.2版本
手动添加用户时提示添加用户请求失败
错误信息如下
`
 <pre>
            ReferenceError: require is not defined<br>
            &nbsp;&nbsp;at callback (file:///usr/src/app/nv-modules/init_default_users_api.js:284:31)<br>
            &nbsp;&nbsp;at file:///usr/src/app/nv-modules/init.js:199:18<br>
            &nbsp;&nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br>
            &nbsp;&nbsp;at next (/usr/src/app/node_modules/express/lib/router/route.js:149:13)<br>
            &nbsp;&nbsp;at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:119:3)<br>
            &nbsp;&nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br>
            &nbsp;&nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:284:15<br>
            &nbsp;&nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)<br>
            &nbsp;&nbsp;at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)<br>&nbsp;&nbsp;at serveStatic (/usr/src/app/node_modules/serve-static/index.js:75:16)
        </pre>
`

**Comment by conanliuhuan** [comment]
未发现此问题。若更新后问题已解决请主动close
