### ISSUE TITLE
[repo]repo源中发布的草稿内容可通过别名方式访问

### ISSUE THREAD

**Issue by LegnaOS** [nvPress/nvPress#5]
repo 仓库中，存在一处问题
1、创建一个新主题，提供了一个别名为 atheme
2、发布该主题
3、编辑该主题，状态为草稿，并保存
4、修改访问地址，可以通过 atheme 这个别名访问该主题（repo 前台不可见）
====
测试环境为在 Next 程序下执行访问源测试
访问链接为（该页面未发布）
`/nv-admin/package-hub/detail?package=samsaraes`

**Comment by conanliuhuan** [comment]
下一版本已解决此问题
