### ISSUE TITLE
[Next]使用 ES 版网页弹窗中，编辑器可正常显示 Block，前端 页面显示异常

### ISSUE THREAD

**Issue by LegnaOS** [nvPress/nvPress#6]
使用框架为 NVPRESS Next
受影响模块：网页弹窗（ES）
问题表现：
后台编辑器中 Block 显示正常
![image](https://github.com/nvPress/nvPress/assets/19571100/42db34ab-1ee7-40d0-aca2-4d0acff12d61)
前端页面不显示
![image](https://github.com/nvPress/nvPress/assets/19571100/b4056286-10f0-45b3-a2a1-501d7285a8f4)
======
Chrome 版本：
版本 126.0.6460.0（正式版本）canary (arm64)
系统版本：macOS Sonoma 14.2

**Comment by conanliuhuan** [comment]
我记得两周前已解决，已解决的bug请注意手动关闭一下
